---
- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- name: Create the user account
  user: name={{ ryane_dotfiles_user_name }}
        password={{ RYANE_DOTFILES_PASSWORD }}
        shell=/bin/zsh

- name: Add user to sudoers
  lineinfile: dest=/etc/sudoers
              regexp="{{ ryane_dotfiles_user_name }} ALL"
              line="{{ ryane_dotfiles_user_name }} ALL=(ALL) ALL"
              state=present

- name: Add my public key to the server
  authorized_key: user={{ ryane_dotfiles_user_name }}
                  key="{{ item }}"
  with_items: ryane_dotfiles_public_keys

- name: Install oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git
       dest=/home/{{ ryane_dotfiles_user_name }}/.oh-my-zsh
  sudo_user: "{{ ryane_dotfiles_user_name }}"

- name: Clone ryane/dotfiles
  git: repo=https://github.com/ryane/dotfiles.git
       dest=/home/{{ ryane_dotfiles_user_name }}/{{ ryane_dotfiles_dotfiles_directory }}

- name: Check state of .zshrc file
  stat: path=/home/{{ ryane_dotfiles_user_name }}/.zshrc
  register: zshrc

- name: Backup existing .zshrc file if it exists
  command: cp /home/{{ ryane_dotfiles_user_name }}/.zshrc /home/{{ ryane_dotfiles_user_name }}/.zshrc.bak
  when: zshrc.stat.exists and zshrc.stat.isreg

- name: Delete existing .zshrc file if it exists
  file: name=/home/{{ ryane_dotfiles_user_name }}/.zshrc
        state=absent
  when: zshrc.stat.exists and zshrc.stat.isreg

- name: Install dotfiles
  shell: ./install.sh --skip-bundle
  args:
    executable: /bin/bash
    chdir: /home/{{ ryane_dotfiles_user_name }}/{{ ryane_dotfiles_dotfiles_directory }}
    creates: /home/{{ ryane_dotfiles_user_name }}/.zshrc
  sudo_user: "{{ ryane_dotfiles_user_name }}"

- name: Setup vim tomorrow theme
  shell: ./install-tomorrow-theme.sh
  args:
    executable: /bin/bash
    chdir: /home/{{ ryane_dotfiles_user_name }}/{{ ryane_dotfiles_dotfiles_directory }}
    creates: /home/{{ ryane_dotfiles_user_name }}/.vim/colors/Tomorrow.vim
  sudo_user: "{{ ryane_dotfiles_user_name }}"

- name: Install vundle to manage vim plugins
  git: repo=https://github.com/gmarik/vundle.git
       dest=/home/{{ ryane_dotfiles_user_name }}/.vim/bundle/vundle
  sudo_user: "{{ ryane_dotfiles_user_name }}"

- name: Check if vim plugins are installed
  shell: ls -l | grep -c ^d
  args:
    executable: /bin/bash
    chdir: /home/{{ ryane_dotfiles_user_name }}/.vim/bundle
  sudo_user: "{{ ryane_dotfiles_user_name }}"
  register: vim_bundle_count
  changed_when: false

- name: Install vim plugins
  shell: /usr/bin/vim -e +BundleInstall +qall
  args:
    executable: /bin/bash
    executable: /bin/bash
    chdir: /home/{{ ryane_dotfiles_user_name }}/{{ ryane_dotfiles_dotfiles_directory }}
  when: vim_bundle_count.stdout|int <= 1
  register: vim_bundle
  sudo_user: "{{ ryane_dotfiles_user_name }}"

- name: Debug vim_bundle
  debug: var=vim_bundle